version: 2
build:
  #image: latest
  os: "ubuntu-20.04"
  tools:
    python: "3.12"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .                # installs wsuconnect package from setup.py
      extra_requirements:
        - docs               # optional if you define extras_require in setup.py
    - requirements: docs/requirements.txt
  

formats:
  - epub
  - pdf